Bug 1182667: Define PRNG_MAX_ADDITIONAL_BYTES as a macro to avoid the unused variable warning in some 32-bit builds.
Here is the compiler warning generated by clang on Mac OS X:
drbg.c:27:22: error: unused variable 'PRNG_MAX_ADDITIONAL_BYTES'
      [-Werror,-Wunused-const-variable]
static const PRInt64 PRNG_MAX_ADDITIONAL_BYTES = LL_INIT(0x1, 0x0);
                     ^

TBR=mt,rrelyea