Bug 1182667: Remove the statement that assigns an enum value (int) to the |data| member (unsigned char *) of a SECItem.
This statement causes a compiler warning. It actually has no effect
because the pkix_pl_LdapDefaultClient_VerifyBindResponse call overwrites
the |msg| structure when it returns rv=SECSuccess, and we only inspect
|msg| when rv == SECSuccess. Here is the compiler warning generated by
clang on Mac OS X:

pkix_pl_ldapdefaultclient.c:365:59: error: incompatible integer to pointer
      conversion assigning to 'unsigned char *' from 'int'
      [-Werror,-Wint-conversion]
        msg.protocolOp.op.bindResponseMsg.resultCode.data = OTHER;
                                                          ^ ~~~~~

TBR=mt